// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EdIlyin.Elm.Core")>]
[<assembly: AssemblyProductAttribute("EdIlyin.Elm.Core")>]
[<assembly: AssemblyDescriptionAttribute("Brings to the F# Elm language core package modules like Json.Encode, Json.Decode, Basics, Debug, Result, Tuple, etc")>]
[<assembly: AssemblyVersionAttribute("1.0.6")>]
[<assembly: AssemblyFileVersionAttribute("1.0.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EdIlyin.Elm.Core"
    let [<Literal>] AssemblyProduct = "EdIlyin.Elm.Core"
    let [<Literal>] AssemblyDescription = "Brings to the F# Elm language core package modules like Json.Encode, Json.Decode, Basics, Debug, Result, Tuple, etc"
    let [<Literal>] AssemblyVersion = "1.0.6"
    let [<Literal>] AssemblyFileVersion = "1.0.6"
    let [<Literal>] AssemblyConfiguration = "Release"
