// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EdIlyin.FSharp.Elm.Core")>]
[<assembly: AssemblyProductAttribute("EdIlyin.FSharp.Elm.Core")>]
[<assembly: AssemblyDescriptionAttribute("Brings to the F# Elm language core package modules like Json.Encode, Json.Decode, Basics, Debug, Result, Tuple, etc")>]
[<assembly: AssemblyVersionAttribute("2.1.0")>]
[<assembly: AssemblyFileVersionAttribute("2.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EdIlyin.FSharp.Elm.Core"
    let [<Literal>] AssemblyProduct = "EdIlyin.FSharp.Elm.Core"
    let [<Literal>] AssemblyDescription = "Brings to the F# Elm language core package modules like Json.Encode, Json.Decode, Basics, Debug, Result, Tuple, etc"
    let [<Literal>] AssemblyVersion = "2.1.0"
    let [<Literal>] AssemblyFileVersion = "2.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
